### ISSUE TITLE
Integration Ha

### ISSUE THREAD

**Issue by nicoxygen** [fmartinou/teleinfo-mqtt#1]
hi would you have an example of lovelace integration, I pasted the code:
- platform: mqtt
   name: teleinfo
   icon: mdi: speedometer
   state_topic: / teleinfo
   json_attributes_topic: / teleinfo
   value_template: "{{value_json.PAPP.value}}"
   unit_of_measurement: VA
  under the sensor heading, the entity goes back well but the integration of commands is not clean would you have an example of lovelace integration, thank you. You weren't on jeedom before!

**Comment by fmartinou** [comment]
Hi @nicoxygen ,

I'm using a [gauge card](https://www.home-assistant.io/lovelace/gauge/) to display the instant consumed power.
![image](https://user-images.githubusercontent.com/16061231/74100482-ce9a8280-4b2f-11ea-813f-8916ac68edea.png)
```yaml
entity: sensor.teleinfo
  max: 11000
  min: 0
  name: Total
  severity:
    green: 0
    red: 9000
    yellow: 7000
  theme: default
  type: gauge
  unit: W
```

And [mini graph cards](https://github.com/kalkih/mini-graph-card) to display the total (/day, /month...) in euros
![image](https://user-images.githubusercontent.com/16061231/74100513-52546f00-4b30-11ea-9cd9-fdae012d2dce.png)
```yaml
aggregate_func: max
entities:
  - entity: sensor.elec_jour_eur
group_by: date
hour24: true
hours_to_show: 168
icon: 'mdi:speedometer'
show:
  graph: bar
type: 'custom:mini-graph-card'
update_interval: 10
```

To compute the consumption /day, /week, it's not that easy; you need to use Rieman sum formula.
Fortunately, HASS provides all the required components to do that.

Below you'll find all the details of my sensor configuration (Heure Creuse / Heure Pleine):
```yaml
input_number:
  edf_hp:
    name: Electricité - Tarif (HP)
    icon: mdi:currency-eur
    unit_of_measurement: eur/MWh
    min: 0
    max: 200
    step: 0.01
    mode: box

  edf_hc:
    name: Electricité - Tarif (HC)
    icon: mdi:currency-eur
    unit_of_measurement: eur/MWh
    min: 0
    max: 200
    step: 0.01
    mode: box

sensor:
  
  # Teleinfo
  - platform: mqtt
    name: teleinfo
    icon: mdi:speedometer
    state_topic: /teleinfo
    json_attributes_topic: /teleinfo
    value_template: "{{ value_json.PAPP.value }}"
    unit_of_measurement: VA

  # Consommation Elec kwh
  - platform: integration
    name: Electricité (Consommation moyenne)
    source: sensor.teleinfo
    unit_prefix: k
    unit: kwh

  - platform: template
    sensors:

      # Consommation Elec jour euro
      elec_jour_eur:
        friendly_name: Electricité (Consommation jour)
        unit_of_measurement: €
        value_template: >
          {{
          (
            states('sensor.electricite_jour_hc')|float * states('input_number.edf_hc')|float / 1000 +
            states('sensor.electricite_jour_hp')|float * states('input_number.edf_hp')|float / 1000
          ) | round(2)
          }}

      # Consommation Elec mois euro
      elec_mois_eur:
        friendly_name: Electricité (Consommation mois)
        unit_of_measurement: €
        value_template: >
          {{
          (
            states('sensor.electricite_mois_hc')|float * states('input_number.edf_hc')|float / 1000 +
            states('sensor.electricite_mois_hp')|float * states('input_number.edf_hp')|float / 1000
          ) | round(2)
          }}

      # Consommation Elec annee euro
      elec_annee_eur:
        friendly_name: Electricité (Consommation année)
        unit_of_measurement: €
        value_template: >
          {{
          (
            states('sensor.electricite_annee_hc')|float * states('input_number.edf_hc')|float / 1000 +
            states('sensor.electricite_annee_hp')|float * states('input_number.edf_hp')|float / 1000
          ) | round(2)
          }}
```
