### ISSUE TITLE
Hass identifier n'apparait pas dans le topic

### ISSUE THREAD

**Issue by WLCD** [fmartinou/teleinfo-mqtt#10]
Bonjour,

Je viens de déployer la version 3.1.0 sur un raspi zero (car la 4.0.0 ne veut pas s'exécuter) et j'ai noté que l'identifiant que j'ai défini dans le conteneur (linky) n'apparait pas dans le topic mqtt 

![Portainer](https://user-images.githubusercontent.com/863737/127734602-29f4bf8f-1e8e-4fb2-b280-a0eb3f3e15aa.png)

Et voici l'ouput coté mqtt

![mqtt_hass](https://user-images.githubusercontent.com/863737/127734676-a4a014b8-5f8f-4004-9362-1a9c224ac894.PNG)

Le tableau JSON avec les valeurs relevées est bien transmis au broker 

Je ne sais donc pas quoi faire de plus, tout à l'air correctement configuré mais le sensor n'apparait pas :/

**Comment by fmartinou** [comment]
Bonjour,

> Je viens de déployer la version 3.1.0 sur un raspi zero (car la 4.0.0 ne veut pas s'exécuter)

Il y a déjà une issue ouverte à ce sujet (https://github.com/fmartinou/teleinfo-mqtt/issues/9) ; je n'ai pas encore investigué.


> l'identifiant que j'ai défini dans le conteneur (linky) n'apparait pas dans le topic mqtt

Ce n'est pas normal en effet :/
Je vais regarder.

En attendant, tu peux supprimer la variable d'env HASS_IDENTIFIER pour lancer le conteneur avec les valeurs par défaut et ça fonctionnera.
(le HASS_IDENTIFIER n'a véritablement d'intérêt que pour ceux qui auraient plusieurs compteurs).

Exemple de ma configuration perso avec laquelle le sensor remonte bien sur home-assistant.

```yaml
  teleinfo:
      image: fmartinou/teleinfo-mqtt:4.0.0
      container_name: teleinfo
      restart: always
      devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
      environment:
          - MQTT_URL=mqtt://mosquitto:1883
```

![image](https://user-images.githubusercontent.com/16061231/127739379-fa9a88b0-7730-4803-b946-0aac6598a355.png)
